const key = "globalTypes";

const SHOW_SIDEBAR = `${key}/SHOW_SIDEBAR`;
const HIDE_SIDEBAR = `${key}/HIDE_SIDEBAR`;
const SHOW_FILTER_PANEL = `${key}/SHOW_FILTER_PANEL`;
const HIDE_FILTER_PANEL = `${key}/HIDE_FILTER_PANEL`;
const SHOW_TICKET_PACKAGE_FORM = `${key}/SHOW_TICKET_PACKAGE_FORM`;
const HIDE_TICKET_PACKAGE_FORM = `${key}/HIDE_TICKET_PACKAGE_FORM`;

export {
  SHOW_SIDEBAR,
  HIDE_SIDEBAR,
  SHOW_FILTER_PANEL,
  HIDE_FILTER_PANEL,
  SHOW_TICKET_PACKAGE_FORM,
  HIDE_TICKET_PACKAGE_FORM,
};
